### ISSUE TITLE
Okta/OIDC support

### ISSUE THREAD

**Issue by dontspamterry** [ArpNetworking/metrics-portal#193]
Does metrics portal have any support for SSO via OIDC/Okta? I took a quick browse through the code and am unable to locate any code which might indicate support for session management and a redirect url on successful authorization via Okta.

**Comment by BrandonArp** [comment]
There is no support for OIDC currently.  This is usually achieved by having a reverse proxy that can front a variety of services behind your SSO provider.  Take a look at https://github.com/zmartzone/mod_auth_openidc as an example.

**Comment by dontspamterry** [comment]
That's exactly the module we're trying to integrate as an OIDC Relying Party. Anyways, the redirect URI is what we're puzzled on since initially, we thought we could set it to some mportal API.
