### ISSUE TITLE
Disable Moving Graphs Under Graph Configure Modal

### ISSUE THREAD

**Issue by vjkoskela** [ArpNetworking/metrics-portal#25]
When showing the graph configuration modal dialog moving graph widgets around should be disabled.

_Repro:_
 - Open Metrics Portal
 - Connect to a host
 - Add a graph
 - Click configure
 - Drag the graph around

_Expected:_ You should not be able to drag graphs around when displaying a modal dialog. Furthermore, the dialog should not dim and move behind the black bar at the top. I expect these two issues are actually related.

**Comment by PhoenixRion** [comment]
https://github.com/ArpNetworking/metrics-portal/pull/43
