### ISSUE TITLE
Message Processing Errors

### ISSUE THREAD

**Issue by vjkoskela** [ArpNetworking/metrics-portal#28]
The following issues occur with the latest released version of Metrics Portal.

```
V2Protocol.js:35 Uncaught TypeError: this.graphViewModel.addNewMetric is not a functioni.processMessage @ V2Protocol.js:35receiveData @ ConnectionModel.js:33
```

This also happens with the V1 protocol and although not tested likely with the original unversioned protocol as well.

Another warning reported during connectivity to MAD is:

```
unhandled message: 
V2Protocol.js:46 Object {command: "logsList", data: Object}
command: "logsList"data: Object__proto__: Object}
```

This makes sense when using the V1 protocol handlers, but this connection was on V2:

```
connecting to remet-app1-uat.snc1
ConnectionModel.js:139 Attempting connection to ws://remet-app1-uat.snc1:7090/telemetry/v2/stream; attempt 1
system.js.src.js:82 Binding /assets/html/HeaderViewModel n {autocompleteOpts: Object}
ConnectionModel.js:28 connection opened to remet-app1-uat.snc1
ConnectionModel.js:167 connection established to remet-app1-uat.snc1
```

Although not completely confirmed, connecting to a machine where a service is down and comes up or new metrics are added while connected sometimes fails to update the tree. The first error above may be causing this. After fixing these message processing issues please retest adding services and metrics while connected to see if those are resolved. If not please file a new issue, ideally after identify whether it is a Metrics Portal issue or MAD issue.

**Comment by vjkoskela** [comment]
@BrandonArp was this resolved?

**Comment by BrandonArp** [comment]
First, please stop adding more than 1 bug per issue.  I fixed the add metric problem. The logs part is just not implemented. That UI is not production ready. Feel free to open another issue about the logs functionality.

**Comment by vjkoskela** [comment]
Relax, the report said "The first error above may be causing this", it did not specify whether these were one or two issues. In fact, it even said if there is a separate issue after resolving the first to file another issue. I know you worked on something related to his but did not close or update the issue. So I followed up.

Ville
